const fs = require('fs');
const {
  parseEventsData,
  parseSkuProductMappingData,
  formatEvents,
} = require('./helpers/data-process.js');
const { deleteFile } = require('./helpers/file-manipulation.js');

// We load into memory the csv file generated by dbeaver
const eventsData = fs.readFileSync('data/TEST.csv', { encoding: 'utf8', flag: 'r' });
const EVENT_TYPES_TO_KEEP = [
  'SKU_INBOUNDED',
  'SKU_OUTBOUNDED',
  'SKU_INCREMENTED',
  'SKU_DECREMENTED',
  'SKU_MISSING',
  'SKU_FOUND',
];

// We parse the data into Objects
const events = parseEventsData(eventsData);
const WMSevents = events.filter((event) => event.source === 'WMS');
const relevantEvents = WMSevents.filter((event) =>
  EVENT_TYPES_TO_KEEP.includes(event.payload.type),
);

const skuMappingData = fs.readFileSync('data/sku-mapping2.csv', { encoding: 'utf8', flag: 'r' });
const skuMapping = parseSkuProductMappingData(skuMappingData);

// We format the events and keep only the relevant information
const { events: eventsFormatted, results } = formatEvents(relevantEvents, skuMapping);
deleteFile('data/relevantEvents.csv');

// We save the events to a file
const eventsWriter = fs.createWriteStream('data/relevantEvents.csv', { flags: 'a' });

eventsFormatted.forEach((event) => {
  eventsWriter.write(`${Object.values(event).join()}\n`);
});

console.log(`Events written to file: ${eventsFormatted.length} events`);
console.log(results);
